language: node_js

node_js:
  - "iojs"
  - "iojs-v1.0.4" 
  
env: 
  - TEST_SUITE=node
sudo: false
before_install: 
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g coveralls
  - git submodule update --init --recursive

after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage